### ISSUE TITLE
Can't upgrade to 2.8.1

### ISSUE THREAD

**Issue by adamivancza** [react-native-linear-gradient/react-native-linear-gradient#627]
After updating the library version from `2.7.3` to `2.8.1` these errors started to pop up on our Android builds:

```
* What went wrong:
Execution failed for task ':react-native-linear-gradient:mergeExtDexDebugAndroidTest'.
> Could not resolve all files for configuration ':react-native-linear-gradient:debugAndroidTestRuntimeClasspath'.
   > Failed to transform react-android-0.71.8-debug.aar (com.facebook.react:react-android:0.71.8) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, com.android.build.api.attributes.BuildTypeAttr=debug, dexing-enable-desugaring=false, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: /root/.gradle/caches/transforms-3/8f0dae96af31ecaf4c8b1666b4dbd049/transformed/jetified-react-android-0.71.8-debug-runtime.jar.
         > Error while dexing.
           The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
           android {
               compileOptions {
                   sourceCompatibility 1.8
                   targetCompatibility 1.8
               }
           }
           See https://developer.android.com/studio/write/java8-support.html for details. Alternatively, increase the minSdkVersion to 24 or above.
```

I tried doing both suggestions (increasing minSdkVersion to 24 and adding complieOptions) but none of them worked.

Any idea what can cause this?

**Comment by friederbluemle** [comment]
Hi @adamivancza - Can you please share a bit more about your specific environment, especially the version of React Native you're on? Based on the error message I'm seeing 0.71.8 - Was this a newly created app project or upgraded from an earlier version?
I assume you already tried to clean the project/Gradle build directories?

**Comment by adamivancza** [comment]
Hey @friederbluemle!

Sure thing - see my answers below
* Yes, we use RN 0.71.8
* This is an existing project which was upgraded many times
* Yes, cleared everything and even tried to run this on our CI but failed everywhere with the same message

**Comment by friederbluemle** [comment]
I'm unable to reproduce this locally.
Which version of Java are you using locally (and on CI)? It could be related.

Can you also try the following (in a separate folder):

```
npx react-native init rn0718 --version 0.71.8
cd rn0718
yarn add react-native-linear-gradient@2.8.1
yarn android
```

If this works, then it's possible that something in your build.gradle files was missed while upgrading from earlier versions of RN.

**Comment by adamivancza** [comment]
oh, thank you for the insight @friederbluemle - that indeed works for me as well. will check out my grade file then!

**Comment by friederbluemle** [comment]
Please let us know if you figure out what the issue was. Someone else reported a problem with 2.8.1 in #630 and I'm trying to determine if this is related/the same issue.

**Comment by adamivancza** [comment]
@friederbluemle I've compared my gradle file with the original RN 0.71.8 Gradle file but didn't spot any differences. So I did some googling and stumbled upon a similar error:
https://github.com/OneSignal/react-native-onesignal/issues/1235
https://github.com/OneSignal/react-native-onesignal/pull/1240

So I did the same with a patch and it is working now! 🙌 

```
diff --git a/node_modules/react-native-linear-gradient/android/build.gradle b/node_modules/react-native-linear-gradient/android/build.gradle
index ab43a34..d20ce2a 100644
--- a/node_modules/react-native-linear-gradient/android/build.gradle
+++ b/node_modules/react-native-linear-gradient/android/build.gradle
@@ -29,8 +29,8 @@ android {
         abortOnError false
     }
     compileOptions {
-        sourceCompatibility JavaVersion.VERSION_1_7
-        targetCompatibility JavaVersion.VERSION_1_7
+        sourceCompatibility JavaVersion.VERSION_1_8
+        targetCompatibility JavaVersion.VERSION_1_8
     }
 }
 ```

If you need I can open a PR with this small change.

**Comment by friederbluemle** [comment]
@adamivancza Thanks for the details!

- Currently the Java sources in react-native-linear-gradient are compatible with 1.7 (we do _not_ use any features from 1.8), so while setting it to 1.8 fixes your immediate issue, it's also not ideal (as it shouldn't be necessary)
- Trying to use a 1.8 feature (such as implicit generic typing, see #624) will lead to errors with older versions of React Native, as reported in #623

`compileOptions` was only added in #624 to avoid accidental use of Java 1.8 features which could break the build. The only version released with it was `2.8.1`.

My best guess is that in certain scenarios (likely due to some interaction with _other_ dependencies), declaring the compileOptions like this in a dependency affects the app build (even if it explicitly sets it to 1.8). I repeat part of the quote you found in the other repo:

>[...] some factors such as the version of AndroidX / Jetpack used in other parts of the app's project.

There is an almost infinite number of possible combinations of different dependency/RN versions/environment etc ;)

So, all things considered, I think the safest option would be to **remove `compileOptions` from this library** altogether (basically restore the behavior _before_ 2.8.1): #634. Now that we have an automated integration test with the lowest supported RN version in place (#633), we should be able to catch such incompatibilities at PR stage in the future.

**Comment by friederbluemle** [comment]
https://github.com/react-native-linear-gradient/react-native-linear-gradient/releases/tag/v2.8.2 was just published. Can you please try it? You shouldn't need the local patch anymore.

**Comment by adamivancza** [comment]
> https://github.com/react-native-linear-gradient/react-native-linear-gradient/releases/tag/v2.8.2 was just published. Can you please try it? You shouldn't need the local patch anymore.

yep that works perfectly! thx for the quick fix! 🥇

**Comment by MayoudP** [comment]
Same issue, fix worked as well for me.
