### ISSUE TITLE
Exception thrown while executing UI block: - [BVLinearGradient locations]: selector sent to instance

### ISSUE THREAD

**Issue by ninjz** [react-native-linear-gradient/react-native-linear-gradient#85]
I am getting this issue when switching to a view which renders the Linear gradient component.

<img width="375" alt="screen shot 2016-05-31 at 3 01 06 pm" src="https://cloud.githubusercontent.com/assets/5641860/15687026/b1fe5dde-2740-11e6-95f9-282f1c90341a.png">

This occurred after upgrading my project to RN v0.26.2, and was not having this issue previously when using RN v0.22 up to 0.25.1

**Comment by dlahyani** [comment]
I get this error too on various RN versions (21, 24, 25, haven't tried other versions).
I narrowed it down to [this commit](https://github.com/brentvatne/react-native-linear-gradient/commit/fe55ead1755e5dbdb351a65493dc13b03342fc53). Not sure why but this commit causes the getter of the locations property to be invoked, however this getter is not implemented by `BVLinearGradient` and hence the exception.

This can be solved quite easily by adding a getter to the locations property, but I am not 100% sure this would be the proper solution since I don't completely understand why the code in that commit above would cause this error.

**Comment by dgladkov** [comment]
Can't reproduce this problem. Could you please provide an example of LinearGradient usage that throws the error above?

**Comment by dilbertKocik** [comment]
I get this same error using the following snippet.

```<LinearGradient colors={['#fff', '#1e8ecd']} style={{height: 190, position: 'absolute', top: 0, left: 0, right: 0}} />```

**Comment by ox-michaelradionov** [comment]
Having the same error with react-native 0.20

```
<LinearGradient colors={['#cde6f4', '#fde1e1']}>...</LinearGradient>
```

**Comment by mitulsavani** [comment]
I have same error :(

**Comment by hpmax00** [comment]
Navtie does not get the value fo locations.
